version: '3.1'
services:
  nominatim:
    image: maxboh/nominatim
    #image: lastnico/nominatim
    volumes:
      - ${IMPORT_DATA_DIR:-./volumes/importdata}:/importdata
      - nominatim-app:/app
    environment:
      - PGHOST=postgis
      - PLANET_DATA_URL=${PLANET_DATA_URL:-http://download.geofabrik.de/europe/monaco-latest.osm.pbf}
      - OSM2PGSQL_CACHE=${OSM2PGSQL_CACHE:-14000}
    ports:
      - ${EXTERNAL_PORT:-127.0.0.1:8080}:80
    restart: always
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_DB=nominatim
      - POSTGRES_USER=nominatim
      - POSTGRES_PASSWORD=nominatim
    volumes:
      - nominatim-database:/var/lib/postgresql/data
      - nominatim-app:/app:ro # Needed for the Nominatim PostgreSQL module
      - ./postgis/set-auth.sh:/docker-entrypoint-initdb.d/set-auth.sh
      - ./postgis/skip-initdb-postgis.sh:/docker-entrypoint-initdb.d/postgis.sh
      - ./postgis/tune-postgres.sh:/docker-entrypoint-initdb.d/tune-postgres.sh
    restart: always
volumes:
  nominatim-database:
    external: true
  nominatim-app:
